import torch
import numpy as np
import matplotlib.pyplot as plt


class VAEVisualizer:
    def __init__(self, model, dataloader, device, img_size=28):
        self.model = model
        self.dataloader = dataloader
        self.device = device
        self.img_size = img_size

    @torch.no_grad()
    def plot_latent_grid(self, n=10, z_dims=(0, 1), scale=3):
        """
        Generates a grid of reconstructed images by systematically varying 
        two dimensions of the latent space.

        Parameters:
        -----------
        n : int, optional (default=10)
            The number of images per side of the grid (total images = n*n).
        z_dims : tuple of int, optional (default=(0, 1))
            The indices of the two latent dimensions to be varied in the grid.
        scale : float, optional (default=3)
            The range of values to explore in the latent space (from -scale to +scale).
        
        Note:
        -----
        All other latent dimensions are kept constant based on a real data sample 
        to ensure the generated images remain within a realistic manifold.
        """
        self.model.eval()
        figure = np.zeros((self.img_size * n, self.img_size * n))
        
        
        data, _ = next(iter(self.dataloader)) # returns (images/data, labels)
        mu, log_var = self.model.encoder(data[0:1].to(self.device))
        z = self.model.reparameterize(mu, log_var)

        grid_x = np.linspace(-scale, scale, n)
        grid_y = np.linspace(-scale, scale, n)[::-1]

        for i, yi in enumerate(grid_y):
            for j, xi in enumerate(grid_x):
                z_sample = z.clone() # clones z to new memory space
                z_sample[0, z_dims[0]] = xi
                z_sample[0, z_dims[1]] = yi
                
                recon = self.model.decoder(z_sample)
                img = recon[0].cpu().numpy().reshape(self.img_size, self.img_size)
                figure[i*self.img_size : (i+1)*self.img_size, j*self.img_size : (j+1)*self.img_size] = img

        plt.imshow(figure, cmap="Blues")
        plt.show()

    @torch.no_grad()
    @torch.no_grad()
    def compare_reconstruction(self, sample_idx=0):
        """
        Visualizes a side-by-side comparison between an original image from the 
        dataset and its reconstructed counterpart generated by the VAE.
        
        The method samples an image from the dataloader, passes it through the 
        full VAE pipeline (Encoder -> Reparameterization -> Decoder), and 
        displays both images to evaluate the quality of the learned representation.

        Parameters:
        -----------
        sample_idx : int, optional (default=0)
            The index of the image within the current batch to be reconstructed.
        """
        self.model.eval()
        data, _ = next(iter(self.dataloader)) # returns (images/data, labels)
        sample = data[sample_idx:sample_idx+1].to(self.device)

        mu, log_var = self.model.encoder(sample)
        z = self.model.reparameterize(mu, log_var)
        recon = self.model.decoder(z)

        orig_img = sample[0].cpu().squeeze().numpy()
        recon_img = recon[0].cpu().squeeze().numpy()

        fig, axes = plt.subplots(1, 2, figsize=(8, 4))
        
        axes[0].imshow(orig_img, cmap="Greys_r")
        axes[0].set_title(f"Original (Idx: {sample_idx})")
        axes[0].axis("off")

        axes[1].imshow(recon_img, cmap="Greys_r")
        axes[1].set_title("Reconstructed")
        axes[1].axis("off")

        plt.tight_layout()
        plt.show()